### ISSUE TITLE
Shadows (at least for the yarnball which makes jumping easier)

### ISSUE THREAD

**Issue by snelson3** [snelson3/Happy-Yarnball#35]
Shadows may make platforming easier so they should be working better.

**Comment by bryonf** [comment]
Initial decision states that this issue is now fixed. Will reopen if necessary.

**Comment by bryonf** [comment]
Reopened due to issues with shadows in build.

**Comment by bryonf** [comment]
Issue resolved. Project Quality default setting set shadows to disabled state.
