### ISSUE TITLE
Lower the cat to the right wall at the bottom of the volcano

### ISSUE THREAD

**Issue by snelson3** [snelson3/Happy-Yarnball#43]
So you don't have to jump to reach it (instead just rolling to the side of the lava). This makes the cat seem less like it's standing on a slope where it should be impossible to stand.

**Comment by bryonf** [comment]
There wasn't really a way to resolve this issue simply by lowering the cat. So, instead, I added a "ledge" for the cat to "stand" on to make it seem less like the cat is floating in mid-air. Considering this closed, but will reopen if the fix is deemed insufficient.
